log_level: INFO

storage:
  storage_path: /qdrant/storage
  optimizers:
    default_segment_number: 2
  performance:
    max_search_threads: 0

service:
  host: 0.0.0.0
  http_port: 6333
  grpc_port: 6334
